/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tree */
        get: operations["get_tree_api_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Node */
        post: operations["create_node_api_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Node */
        delete: operations["delete_node_api_nodes__node_id__delete"];
        options?: never;
        head?: never;
        /** Update Node */
        patch: operations["update_node_api_nodes__node_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/wrap-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wrap Up */
        post: operations["wrap_up_api_sessions__session_id__wrap_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile__node_id__get"];
        /** Edit Profile */
        put: operations["edit_profile_api_profile__node_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_api_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/{insight_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Insight Feedback */
        post: operations["post_insight_feedback_api_insights__insight_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnotationOut */
        AnnotationOut: {
            /** Message Id */
            message_id: number;
            /** Concept */
            concept: string | null;
            /** Concept Type */
            concept_type: string | null;
            /** Strategies */
            strategies: string[];
            /** Ordering */
            ordering: string | null;
            /** Verdict */
            verdict: string | null;
            /** Understanding */
            understanding: number | null;
            /** Confidence */
            confidence: number | null;
            /** Referenced Part */
            referenced_part: string | null;
            /** Reasoning */
            reasoning: string | null;
            /** Evaluator */
            evaluator: string | null;
            /** Level Probs */
            level_probs: number[] | null;
            /** Signals */
            signals: {
                [key: string]: number;
            } | null;
        };
        /** EpisodeOut */
        EpisodeOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Concept */
            concept: string;
            /** Concept Type */
            concept_type: string;
            /** Outcome */
            outcome: string;
            /** Message Ids */
            message_ids: number[];
            /** Click Message Id */
            click_message_id: number | null;
            /** Winning Message Id */
            winning_message_id: number | null;
            /** Path Summary */
            path_summary: string;
            /** Why It Clicked */
            why_it_clicked: string;
            /** Prompting Moves */
            prompting_moves: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightAction */
        InsightAction: {
            /**
             * Action
             * @enum {string}
             */
            action: "confirm" | "reject" | "dismiss";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** InsightOut */
        InsightOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Status */
            status: string;
            /** Node Id */
            node_id: number | null;
            /** Scope */
            scope: string;
            /** Session Id */
            session_id: number | null;
            /** Pattern Id */
            pattern_id: number | null;
            /** Evidence */
            evidence: components["schemas"]["EpisodeOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NodeCreate */
        NodeCreate: {
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "folder" | "session";
            /** Title */
            title: string;
        };
        /** NodeOut */
        NodeOut: {
            /** Id */
            id: number;
            /** Parent Id */
            parent_id: number | null;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NodeUpdate */
        NodeUpdate: {
            /** Title */
            title?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Move
             * @default false
             */
            move: boolean;
        };
        /** PatternOut */
        PatternOut: {
            /** Id */
            id: number;
            /** Claim */
            claim: string;
            /** Strategy */
            strategy: string;
            /** Concept Type */
            concept_type: string | null;
            /** Confidence */
            confidence: number;
            /** Evidence Count */
            evidence_count: number;
            /** User Status */
            user_status: string;
            /** User Note */
            user_note: string;
            /** Source */
            source: string;
        };
        /** ProfileEdit */
        ProfileEdit: {
            /** Markdown */
            markdown: string;
        };
        /** ProfileEditOut */
        ProfileEditOut: {
            /** Understood */
            understood: string;
            /** Ops */
            ops: string[];
            /** Markdown */
            markdown: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Node Id */
            node_id: number | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Markdown */
            markdown: string;
            /** Patterns */
            patterns: components["schemas"]["PatternOut"][];
            /** Stickies */
            stickies: components["schemas"]["StickyOut"][];
            /** Tutor Sees */
            tutor_sees: string;
        };
        /** SendMessage */
        SendMessage: {
            /** Content */
            content: string;
        };
        /** SessionOut */
        SessionOut: {
            node: components["schemas"]["NodeOut"];
            /** Path */
            path: string;
            /** Summary */
            summary: string;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            /** Annotations */
            annotations: components["schemas"]["AnnotationOut"][];
            /** Episodes */
            episodes: components["schemas"]["EpisodeOut"][];
            /** Pending Jobs */
            pending_jobs: number;
            /** Failed Jobs */
            failed_jobs: string[];
        };
        /** StickyOut */
        StickyOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Concept */
            concept: string;
            /** Excerpt */
            excerpt: string;
            /** Why */
            why: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_tree_api_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeOut"][];
                };
            };
        };
    };
    create_node_api_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_api_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_api_nodes__node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wrap_up_api_sessions__session_id__wrap_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_profile_api_profile__node_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileEditOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_api_insights_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_insight_feedback_api_insights__insight_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insight_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsightAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
