/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tree */
        get: operations["get_tree_api_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Node */
        delete: operations["delete_node_api_nodes__node_id__delete"];
        options?: never;
        head?: never;
        /** Update Node */
        patch: operations["update_node_api_nodes__node_id__patch"];
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Export
         * @description Body: the claude.ai export ZIP (or conversations.json) as raw bytes.
         */
        post: operations["import_export_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Estimate */
        get: operations["get_estimate_api_analysis_estimate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analysis */
        post: operations["start_analysis_api_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["latest_run_api_analysis_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["get_topic_api_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_api_chats__chat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Chat
         * @description Override the classifier: include a chat it skipped (it's analyzed on the next run), or leave one out.
         */
        patch: operations["update_chat_api_chats__chat_id__patch"];
        trace?: never;
    };
    "/api/profile/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile__node_id__get"];
        /** Edit Profile */
        put: operations["edit_profile_api_profile__node_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_api_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/{insight_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Insight Feedback */
        post: operations["post_insight_feedback_api_insights__insight_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ask History */
        get: operations["ask_history_api_ask_get"];
        put?: never;
        /** Ask Question */
        post: operations["ask_question_api_ask_post"];
        /** Clear Ask */
        delete: operations["clear_ask_api_ask_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnotationOut */
        AnnotationOut: {
            /** Message Id */
            message_id: number;
            /** Concept */
            concept: string | null;
            /** Concept Type */
            concept_type: string | null;
            /** Strategies */
            strategies: string[];
            /** Ordering */
            ordering: string | null;
            /** Verdict */
            verdict: string | null;
            /** Understanding */
            understanding: number | null;
            /** Confidence */
            confidence: number | null;
            /** Referenced Part */
            referenced_part: string | null;
            /** Reasoning */
            reasoning: string | null;
            /** Evaluator */
            evaluator: string | null;
            /** Level Probs */
            level_probs: number[] | null;
            /** Signals */
            signals: {
                [key: string]: number;
            } | null;
        };
        /** AskIn */
        AskIn: {
            /** Content */
            content: string;
        };
        /** AskMessageOut */
        AskMessageOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Tools Used */
            tools_used: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatOut */
        ChatOut: {
            chat: components["schemas"]["ChatSummaryOut"];
            /** Breadcrumbs */
            breadcrumbs: components["schemas"]["Crumb"][];
            /** Topic Label */
            topic_label: string | null;
            /** Summary */
            summary: string;
            /** Claude Url */
            claude_url: string | null;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            /** Annotations */
            annotations: components["schemas"]["AnnotationOut"][];
            /** Episodes */
            episodes: components["schemas"]["EpisodeOut"][];
        };
        /** ChatSummaryOut */
        ChatSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Is Learning */
            is_learning: boolean | null;
            /** Judged Turns */
            judged_turns: number;
            /** Avg Understanding */
            avg_understanding: number | null;
            mix: components["schemas"]["Mix"];
        };
        /** ChatUpdate */
        ChatUpdate: {
            /** Is Learning */
            is_learning: boolean;
        };
        /** Crumb */
        Crumb: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** EpisodeOut */
        EpisodeOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Concept */
            concept: string;
            /** Concept Type */
            concept_type: string;
            /** Outcome */
            outcome: string;
            /** Message Ids */
            message_ids: number[];
            /** Click Message Id */
            click_message_id: number | null;
            /** Winning Message Id */
            winning_message_id: number | null;
            /** Path Summary */
            path_summary: string;
            /** Why It Clicked */
            why_it_clicked: string;
            /** Prompting Moves */
            prompting_moves: string[];
        };
        /** Estimate */
        Estimate: {
            /** Chats */
            chats: number;
            /** Turns */
            turns: number;
            /** Usd */
            usd: number;
            /** Breakdown */
            breakdown: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportOut */
        ImportOut: {
            /** New */
            new: number;
            /** Updated */
            updated: number;
            /** Unchanged */
            unchanged: number;
            /** Empty */
            empty: number;
            /** Pending Chats */
            pending_chats: number;
            estimate: components["schemas"]["Estimate"];
        };
        /** InsightAction */
        InsightAction: {
            /**
             * Action
             * @enum {string}
             */
            action: "confirm" | "reject" | "dismiss";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** InsightOut */
        InsightOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Status */
            status: string;
            /** Node Id */
            node_id: number | null;
            /** Scope */
            scope: string;
            /** Session Id */
            session_id: number | null;
            /** Pattern Id */
            pattern_id: number | null;
            /** Evidence */
            evidence: components["schemas"]["EpisodeOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Mix */
        Mix: {
            /** Understood */
            understood: number;
            /** Iffy */
            iffy: number;
            /** Not Understood */
            not_understood: number;
        };
        /** NodeOut */
        NodeOut: {
            /** Id */
            id: number;
            /** Parent Id */
            parent_id: number | null;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Is Learning */
            is_learning: boolean | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NodeUpdate */
        NodeUpdate: {
            /** Title */
            title?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Move
             * @default false
             */
            move: boolean;
        };
        /** OverviewOut */
        OverviewOut: {
            snapshot: components["schemas"]["SnapshotOut"] | null;
            stats: components["schemas"]["Stats"];
            mix: components["schemas"]["Mix"];
            /** Topics */
            topics: components["schemas"]["TopicOut"][];
            /** Global Patterns */
            global_patterns: components["schemas"]["PatternOut"][];
            /** Top Patterns */
            top_patterns: components["schemas"]["PatternOut"][];
            /** Stickies */
            stickies: components["schemas"]["StickyOut"][];
        };
        /** PatternOut */
        PatternOut: {
            /** Id */
            id: number;
            /** Claim */
            claim: string;
            /** Strategy */
            strategy: string;
            /** Concept Type */
            concept_type: string | null;
            /** Confidence */
            confidence: number;
            /** Evidence Count */
            evidence_count: number;
            /** User Status */
            user_status: string;
            /** User Note */
            user_note: string;
            /** Source */
            source: string;
            /** Scope Id */
            scope_id: number | null;
            /** Scope */
            scope: string;
            /** Topics */
            topics: string[];
        };
        /** ProfileEdit */
        ProfileEdit: {
            /** Markdown */
            markdown: string;
        };
        /** ProfileEditOut */
        ProfileEditOut: {
            /** Understood */
            understood: string;
            /** Ops */
            ops: string[];
            /** Markdown */
            markdown: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Node Id */
            node_id: number | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Markdown */
            markdown: string;
            /** Patterns */
            patterns: components["schemas"]["PatternOut"][];
            /** Stickies */
            stickies: components["schemas"]["StickyOut"][];
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            /** Stage Done */
            stage_done: number;
            /** Stage Total */
            stage_total: number;
            /** Chats */
            chats: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Errors */
            errors: string[];
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Headline */
            headline: string;
            /** Summary Md */
            summary_md: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StartAnalysis */
        StartAnalysis: {
            /** Limit */
            limit?: number | null;
        };
        /** Stats */
        Stats: {
            /** Chats */
            chats: number;
            /** Learning Chats */
            learning_chats: number;
            /** Analyzed Chats */
            analyzed_chats: number;
            /** Pending Chats */
            pending_chats: number;
            /** Topics */
            topics: number;
        };
        /** StickyOut */
        StickyOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Chat Title */
            chat_title: string;
            /** Concept */
            concept: string;
            /** Excerpt */
            excerpt: string;
            /** Why */
            why: string;
        };
        /** TopicDetailOut */
        TopicDetailOut: {
            topic: components["schemas"]["TopicOut"];
            /** Summary */
            summary: string;
            /** Breadcrumbs */
            breadcrumbs: components["schemas"]["Crumb"][];
            /** Children */
            children: components["schemas"]["TopicOut"][];
            /** Patterns */
            patterns: components["schemas"]["PatternOut"][];
            /** Stickies */
            stickies: components["schemas"]["StickyOut"][];
            /** Chats */
            chats: components["schemas"]["ChatSummaryOut"][];
        };
        /** TopicOut */
        TopicOut: {
            /** Id */
            id: number;
            /** Parent Id */
            parent_id: number | null;
            /** Title */
            title: string;
            /** Path */
            path: string;
            /** Chat Count */
            chat_count: number;
            /** Analyzed Count */
            analyzed_count: number;
            /** Judged Turns */
            judged_turns: number;
            /** Avg Understanding */
            avg_understanding: number | null;
            mix: components["schemas"]["Mix"];
            /** Line */
            line: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_tree_api_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeOut"][];
                };
            };
        };
    };
    delete_node_api_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_api_nodes__node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_export_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
        };
    };
    get_estimate_api_analysis_estimate_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estimate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_api_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAnalysis"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_run_api_analysis_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"] | null;
                };
            };
        };
    };
    get_overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    get_topic_api_topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_api_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_api_chats__chat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_profile_api_profile__node_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileEditOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_api_insights_get: {
        parameters: {
            query?: {
                status?: string | null;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_insight_feedback_api_insights__insight_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insight_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsightAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_history_api_ask_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskMessageOut"][];
                };
            };
        };
    };
    ask_question_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_ask_api_ask_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
